### ISSUE TITLE
无法正确定位当前正在播放的歌曲

### ISSUE THREAD

**Issue by achieve-dream1221** [solstice23/material-you-theme-netease#1]
我先将该主题关掉, 发现能够正确定位歌曲位置, 但是打开后, 定位的位置不正确
# 开启主题前
![image](https://user-images.githubusercontent.com/57209087/210488082-afe8c4e0-cfef-4cd1-abeb-49e080e263c7.png)
# 开启主题后(没有滚动过, 跳转位置不对)
![image](https://user-images.githubusercontent.com/57209087/210488309-e68780e0-3b2c-46fe-93c1-6768e64c78c7.png)

**Comment by solstice23** [comment]
Fixed in https://github.com/solstice23/material-you-theme-netease/commit/9d029e06429ad8fa07d47ee92749069c2cc6cebf
