### ISSUE TITLE
与Apple Music-like lyrics配合使用时，评论区字体颜色可能不匹配

### ISSUE THREAD

**Issue by yijiaqu** [solstice23/material-you-theme-netease#11]
使用亮色主题时，评论区字体颜色为黑色，此时若背景为深色，则看不清评论区
![QQ截图20230114114039](https://user-images.githubusercontent.com/57066567/212449186-93c7ed4a-ddba-4898-8f8d-3cc3d9592fa4.png)
![QQ截图20230114114050](https://user-images.githubusercontent.com/57066567/212449187-1680bacd-24e7-4b69-abc0-140efe6d4eff.png)
是否可以实现评论区字体颜色自适应？
感谢作者。

**Comment by solstice23** [comment]
其实卸载 MaterialYouTheme 应该也会这样的，测试一下
如果是的话，请去 Apple Lyric Repo 发 issue

**Comment by ningguolin** [comment]
今天applemusic like lyrics已经将该问题想办法修复，已支持调节背景亮度+30%亮度就能看清评论区了
