### ISSUE TITLE
歌手主页没有个人主页图标

### ISSUE THREAD

**Issue by EXSPIRAVIT1104OFFICIAL** [solstice23/material-you-theme-netease#12]
歌手主页上的个人主页按钮就是一个方形的图层没有任何图标
![图片](https://user-images.githubusercontent.com/80319225/212463829-507672e8-c90c-4f91-8600-0c5ed9f79b50.png)

**Comment by zhuzixuan2019241** [comment]
+1

**Comment by solstice23** [comment]
已修复
