### ISSUE TITLE
安装插件后无法正常显示UI

### ISSUE THREAD

**Issue by YSYD0315** [solstice23/material-you-theme-netease#16]
如题 UI部件几乎无法分辨 BetterNCM版本1.0.0 本插件2.0.1 原主题为酷炫黑
![image](https://user-images.githubusercontent.com/96107277/214348802-54df94d1-6170-42d0-bc28-acc89148e76a.png)
尝试更改主题为亮色主题后仍无法正常显示(上传抽风了, 文字能正常显示,但是除文字与图片以外其他完全不能分辨)
以及点击"打开设置面板"无法触发设置界面

**Comment by youensChen** [comment]
同样的问题，系统win11，其他东西都是最新版，有什么解决办法么😂

**Comment by solstice23** [comment]
升级网易云版本，BetterNCM 装 nightly

**Comment by youensChen** [comment]
> 升级网易云版本，BetterNCM 装 nightly
BetterNCM 是 nightly版本，原主题为酷炫黑还是有这个显示问题，实测将主题改为中国红后再安装就没问题了

**Comment by YSYD0315** [comment]
> 升级网易云版本，BetterNCM 装 nightly

感谢,问题已解决. 网易云已更新至2.10.6(200601) betterNCM 版本为1.0.0-nightly. **尝试更改为稳定版1.0.0后也同样可用**, 可能是网易云软件相关导致的问题.


> > 升级网易云版本，BetterNCM 装 nightly
BetterNCM 是 nightly版本，原主题为酷炫黑还是有这个显示问题，实测将主题改为中国红后再安装就没问题了

我是Win10 21H2, 更新版本后酷炫黑也可以直接安装使用.

_个人附注:在旧版本下部分BetterNCM的部件点击也没有反应, 更新后同样得到解决, 请后来者以此作为参考_
