### ISSUE TITLE
部分排行榜歌曲列表显示错位

### ISSUE THREAD

**Issue by avgtech674** [solstice23/material-you-theme-netease#19]
![image](https://user-images.githubusercontent.com/61078997/215238296-c8d026ed-8260-4988-85d2-c82d39b40db5.png)
如图，新歌榜详情界面的歌曲列表出现显示错位问题。
经本人测试，实际上所有会显示歌曲相对排名变化的排行榜都有同样的问题；重载插件无效，且已排除其他插件干扰。

**Comment by LiTaJam** [comment]
+1，同样遇到这个问题，删除所有插件，重装主题也没有解决，win11 22H2
![image](https://user-images.githubusercontent.com/78863126/215318914-9917bc7a-ebea-4450-be2d-4920234a3d72.png)

**Comment by luobr233** [comment]
+1

**Comment by MKingss** [comment]
问题同上

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/216072171-d8d5dc19-ede3-4e39-ad8a-d8ecc2555477.png)
无法复现，要进入哪个页面

**Comment by LiTaJam** [comment]
> ![image](https://user-images.githubusercontent.com/23134847/216072171-d8d5dc19-ede3-4e39-ad8a-d8ecc2555477.png) 无法复现，要进入哪个页面

打开排行榜页面进入任意一个排行榜单
![image](https://user-images.githubusercontent.com/78863126/216089436-6a28bfc0-8c6c-4e7d-a3b7-b56f30ec55e0.png)
