### ISSUE TITLE
有关播放列表中被选取歌曲突出显示的问题

### ISSUE THREAD

**Issue by JersyJL** [solstice23/material-you-theme-netease#2]
使用主题后，选择播放列表中的歌曲时没有将被选歌曲突出显示（被选中后没有鼠标悬停在歌曲上的那种突出显示），被选歌曲与没有选择的歌曲外观上没有差别

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/210989393-01d5442f-2e12-4213-8354-d24cd90ce3c1.png)

**Comment by JersyJL** [comment]
> ![image](https://user-images.githubusercontent.com/23134847/210989393-01d5442f-2e12-4213-8354-d24cd90ce3c1.png)
> 
> 43 选中 45 悬停 无法复现

![GIF 2023-1-6 18-41-48](https://user-images.githubusercontent.com/107380731/210993836-d99b08b1-f11b-48eb-8b6b-2045257be099.gif)
抱歉，是我表达的不是很准确。
是那个底栏右下角的播放列表，就是顶上是“当前播放”的那个。这个gif里，鼠标点击的时候没有选中的突出显示，但是确实是选中了
