### ISSUE TITLE
支持 Mac 版本的网易云音乐

### ISSUE THREAD

**Issue by Steve-xmh** [solstice23/material-you-theme-netease#21]
如题，现在 Material You 插件在 Mac 版网易云里长这样：

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/39523898/215309885-d07294cf-9642-4968-9b12-a4f4bc128603.png">
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/39523898/215309921-68251f48-4358-4e18-a887-6792f89ec346.png">

~~好吧其实我是来捣乱的（逃）~~

~~但是如果真的能支持的话就太好了~~

**Comment by solstice23** [comment]
手上没有 Mac 设备（）

而且看上去页面结构变化挺大的？应该要完全重写了

**Comment by Steve-xmh** [comment]
> 手上没有 Mac 设备（）
> 
> 而且看上去页面结构变化挺大的？应该要完全重写了

与其说变化大，不如说是多老的东西了（）

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/39523898/215323059-60e93a3d-f1e9-4566-a90a-aaf0d2c9af97.png">

**Comment by Steve-xmh** [comment]
> 手上没有 Mac 设备（）
> 
> 而且看上去页面结构变化挺大的？应该要完全重写了

与其说变化大，不如说是多老的东西了（）

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/39523898/215323059-60e93a3d-f1e9-4566-a90a-aaf0d2c9af97.png">

**Comment by ningguolin** [comment]
捕捉AppleMusic Like Lyrics开发者大佬

**Comment by cale044** [comment]
> 手上没有 Mac 设备（）
> 
> 而且看上去页面结构变化挺大的？应该要完全重写了

也许你可以搞一个《嘿》苹果
