### ISSUE TITLE
【bug】排行榜界面错位

### ISSUE THREAD

**Issue by cow-your-sister** [solstice23/material-you-theme-netease#28]
![微信截图_20230203211506](https://user-images.githubusercontent.com/88882901/216612660-b5c1d53d-c364-4da7-ac96-5f7c5a90827a.png)
这几个排行榜的界面
![微信截图_20230203211518](https://user-images.githubusercontent.com/88882901/216612683-87e73ca4-5a7f-4f82-9d7b-fc90070de86c.png)
都错位了

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/216612789-434d127e-9375-4b07-8659-9c65510f7b63.png)
![image](https://user-images.githubusercontent.com/23134847/216612829-ffe00bda-6be5-448e-9743-55fac3f58849.png)

**Comment by MKingss** [comment]
啊啊，我怎么还有这个问题啊

**Comment by solstice23** [comment]
@MKingss 忘记发版了

**Comment by MKingss** [comment]
@solstice23 哦哦
