### ISSUE TITLE
播放图标和歌单图标重叠

### ISSUE THREAD

**Issue by Ling-Zero** [solstice23/material-you-theme-netease#30]
如图，这是我设置问题还是bug
![image](https://user-images.githubusercontent.com/89287049/216800924-e66892a3-6302-4810-a8a2-4ec3bdb7e065.png)
![image](https://user-images.githubusercontent.com/89287049/216800933-d88a62b4-531c-40a5-bc21-bf6af27642be.png)

**Comment by solstice23** [comment]
snippet 的问题
