### ISSUE TITLE
进度条顺滑和material you在播放界面进度条BUG

### ISSUE THREAD

**Issue by HandsomeYDZ** [solstice23/material-you-theme-netease#34]
播放进度条错位，另外图标有一丢丢小问题（和重新定义播放界面那个插件）
![87H~17GS_D5B6D__B`(9S@9](https://user-images.githubusercontent.com/124165820/217271463-c49d4de7-9a14-48e3-9235-f6493385482a.png)
![FJTWWH`PY`(@BQ5C%P 71TM](https://user-images.githubusercontent.com/124165820/217271486-ea720bac-a4be-453f-a6d4-7d801479870e.png)

**Comment by HandsomeYDZ** [comment]
![87H~17GS_D5B6D__B`(9S@9](https://user-images.githubusercontent.com/124165820/217271670-793118fa-62dc-4be2-a4d5-ab81e0de4b8c.png)

**Comment by solstice23** [comment]
两个插件都更新到最新

**Comment by HandsomeYDZ** [comment]
已经是最新的2.0.8和2.5.0了，emmmm

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/217272158-ec74e6b2-7d4d-4943-a11e-b7c6ea850829.png)
这个关了吗，打开再关闭试试

**Comment by HandsomeYDZ** [comment]
在最新版的RefinedNowPlaying>2.5.0< 里面好像去掉了正在播放页面中不应用主题这个按钮诶emmm，是我没找到吗

**Comment by solstice23** [comment]
这个是 MDYou 的设置

**Comment by HandsomeYDZ** [comment]
emmmm他默认是关闭的（在默认关闭的情况下出现的这个问题？），然后我打开后再关闭就解决了，谢谢

**Comment by solstice23** [comment]
这个是因为我之前版本写炸了 现在虽然修了但需要开关一次
