### ISSUE TITLE
进入MV或视频播放界面后再返回，侧边栏一片空白

### ISSUE THREAD

**Issue by chen310** [solstice23/material-you-theme-netease#37]
os: win11 22H2
BetterNCM: 1.0.1
Material You: 2.0.8
![cloudmusic_AnuplqsgLs](https://user-images.githubusercontent.com/33364396/217718176-8f358dd8-9045-4a61-afbd-cf09aed032d0.png)

**Comment by solstice23** [comment]
已在betterncm本体修复
