### ISSUE TITLE
底部暂停后，拖动进度条自动播放bug

### ISSUE THREAD

**Issue by ZacharyBacon** [solstice23/material-you-theme-netease#38]
版本：2.0.8
你好，作者，我无意间发现一个问题，底部暂停后，拖动进度条自动播放,但是底部显示的是暂停键，导致歌词位置不对，底部播放暂停不能用。需要手动播放，然后还是无效果，还要再暂停播放即可，但是歌词位置无法恢复。我需要怎么做，才可以避免出现这种问题？

**Comment by ZacharyBacon** [comment]
![图片](https://user-images.githubusercontent.com/41818833/217772983-406bfec8-5d55-4dec-821e-e56e689ac5e5.png)
![图片](https://user-images.githubusercontent.com/41818833/217773019-cb3d14e2-3bea-48e4-adba-a7911977d4c7.png)
第一张是我正常播放时，歌词正常滚动，第二张图是我点了一下进度条，歌词无法跳转到正常的位置

**Comment by solstice23** [comment]
应该是 FluentProgressBar 或者别的东西的问题，和主题无关
