### ISSUE TITLE
是否考虑出一个只有一种主色调的动态主题？

### ISSUE THREAD

**Issue by windy1021** [solstice23/material-you-theme-netease#45]
背景颜色一直变来变去看不太习惯？（可能只有我🤣）仅仅提个建议，或者是否考虑自定义主题也可以有白天和晚上两个模式根据时间变化？

**Comment by windy1021** [comment]
或者是否考虑可以多保存几个自定义配置的方案？可以让用户根据不同时间自由切换之类的，甚至还可以做成一个配置市场给其他用户提供参考😂

**Comment by solstice23** [comment]
ok了
