### ISSUE TITLE
与自身不兼容

### ISSUE THREAD

**Issue by achieve-dream1221** [solstice23/material-you-theme-netease#46]
## 如题, 插件商店显示与本身不兼容, 虽然不影响正常使用, 但是很别扭
![image](https://user-images.githubusercontent.com/57209087/220072246-d71fb799-1a34-455e-ad5f-4701d6730316.png)

**Comment by solstice23** [comment]
和主题无关

**Comment by achieve-dream1221** [comment]
哦,好吧
