### ISSUE TITLE
可否多保存几个自定义配置方案？

### ISSUE THREAD

**Issue by windy1021** [solstice23/material-you-theme-netease#47]
配置1，配置2......多几个方案好选/[受虐滑稽]

**Comment by solstice23** [comment]
@windy1021 泪目 这个功能居然有人用

**Comment by solstice23** [comment]
@windy1021 使用率应该不高 没动力做 不过有好的配色方案可以截图然后直接PR到这里 进去默认预设

**Comment by windy1021** [comment]
有哇有哇，有些方案挺喜欢的但是总有些配色感觉差了一丢丢感觉所以就更愿意去自己配一个
<img src="https://files.catbox.moe/lc06ps.png"  />
这个怎么样，我个人比较喜欢这种浅色看着挺舒服的，可以进预设的话名字可不可以叫 Cloud ＆ Moon
因为灵感是这张图<img src="https://files.catbox.moe/qndk88.jpg"  />
谢谢大大开发这么好的插件~辛苦啦

**Comment by solstice23** [comment]
需要我标明贡献者吗

**Comment by windy1021** [comment]
> 

不用啦，能命名已经很不错了哈哈哈，谢谢大大

**Comment by solstice23** [comment]
确实很好看! 新版已经发了

![image](https://user-images.githubusercontent.com/23134847/220827538-d8551669-d306-48d7-84f5-37cbdfe18cf1.png)
