### ISSUE TITLE
正在播放页面的进度条不会自动隐藏，在看歌词的时候有点突兀

### ISSUE THREAD

**Issue by nieeng** [solstice23/material-you-theme-netease#52]
![ED1LH}%4U(3LFRK8Z_(N8 I](https://user-images.githubusercontent.com/126376220/221395483-454caeb0-bb20-41e2-800f-32dae2ca6a4c.png)
这个进度条隐藏原版的有，但这个没有，用起来突兀

**Comment by solstice23** [comment]
打开这个开关 ![image](https://user-images.githubusercontent.com/23134847/221395530-fcfac8a0-2ded-4342-aab2-9ad053e7ed49.png)
或者安装播放界面美化插件
