### ISSUE TITLE
私人FM得收藏窗口UI无法正常显示

### ISSUE THREAD

**Issue by mslkyy** [solstice23/material-you-theme-netease#67]
操作系统：Windows 10 Version 22H2
网易云音乐版本：2.10.7
BetterNCM版本：1.2.0
![image](https://user-images.githubusercontent.com/57085983/230714349-542e009f-094b-4643-8c8a-3dd0327c3adb.png)

**Comment by rainyorange** [comment]
不止收藏 基本fm的所有窗口都寄了
![image](https://user-images.githubusercontent.com/36807368/232533878-a5fba0bb-d509-4ad3-89eb-5816878e3cf5.png)
