### ISSUE TITLE
可不可以关闭侧边栏的一些tag?

### ISSUE THREAD

**Issue by Lanturewen** [solstice23/material-you-theme-netease#69]
![image](https://user-images.githubusercontent.com/18157343/231675434-0eb404c1-a7ea-47c1-b604-f67c7fa1de63.png)
如图,可以去掉直播, 博客这些tag吗? 我看作者的截图是没有的,是需要降级版本吗?

**Comment by solstice23** [comment]
@Lanturewen Tiny NCM
