### ISSUE TITLE
评论区Hover评论闪烁

### ISSUE THREAD

**Issue by shiina7** [solstice23/material-you-theme-netease#73]
鼠标放在评论区两条评论之间 很容易触发闪烁 如图：
![animate](https://github.com/solstice23/material-you-theme-netease/assets/59157966/299799d9-e6b9-4ad1-ad87-a8847eb6ddbb)

**Comment by solstice23** [comment]
更新一下网易云

**Comment by shiina7** [comment]
> 更新一下网易云

已解决
