### ISSUE TITLE
定位较长歌单内歌曲时显示定位失败

### ISSUE THREAD

**Issue by zhuzixuan2019241** [solstice23/material-you-theme-netease#8]
定位较长歌单（经测试约1000首以上）内歌曲时显示定位失败，将列表拉到底有页面缓存时则可以定位成功，切换tab页面缓存消失后继续定位失败
![image](https://user-images.githubusercontent.com/68471692/212011543-6b83b988-aec2-4508-b188-fe6865e41c65.png)

**Comment by solstice23** [comment]
原版就这样 基本没办法修的

**Comment by zhuzixuan2019241** [comment]
> 

明白了，谢谢
