### ISSUE TITLE
使用显示异常

### ISSUE THREAD

**Issue by BiXxia** [solstice23/material-you-theme-netease#9]
插件使用错误，界面显示不完整。
<img width="1280" alt="屏幕截图 2023-01-13 232459" src="https://user-images.githubusercontent.com/85838202/212356999-2cb8aa48-c66a-4b99-af28-908c40adfc13.png">
<img width="1280" alt="屏幕截图 2023-01-13 232629" src="https://user-images.githubusercontent.com/85838202/212357002-027df350-e64c-429b-b88a-e3dd2c23134e.png">

**Comment by Rexld** [comment]
> 一样的显示异常，点设置也没反应，是不是win11就会

**Comment by youensChen** [comment]
一样的问题

**Comment by solstice23** [comment]
网易云版本？

**Comment by BiXxia** [comment]
> 网易云版本？

我更新网易云之后就问题不大了，但是还有点毛病
